#include "PokemonLeauge.h"
BEGIN_GAME
CREATE POKEMON { NAME: "Pikachu", TYPE: "Electric", HP: 120 }
CREATE POKEMON { NAME: "Squirtle", TYPE: "Water", HP: 100 }
CREATE POKEMONS [ POKEMON{ NAME: "Ho Oh", TYPE: "Fire", HP: 120 }, POKEMON{ NAME: "Bulbasaur", TYPE: "Grass", HP: 85 } ]
CREATE ABILITY { NAME: "Electric_Shock", ACTION: START IF GET_HP(ATTACKER) < 30 DO HEAL ATTACKER 25 ELSE HEAL ATTACKER 15 END END }
CREATE ABILITY { NAME: "Solar_Power", ACTION: START POKEBALL ATTACKER ---α DAMAGE DEFENDER 20 END }
CREATE ABILITIES [ ABILITY { NAME: "Electric_Shock", ACTION: START IF GET_HP (ATTACKER) < 30 DO HEAL ATTACKER 25 ELSE HEAL ATTACKER 15 END END }, ABILITY { NAME: "Blaze", ACTION: START DAMAGE DEFENDER 22 END } ]
END_GAME
